services:
  - name: server
    plan: Starter
    type: web
    env: node
    repo: https://github.com/mx-ruthie/interview-randomizer.git
    buildCommand: npm install && npm run build && cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db
          property: connectionString

databases:
  - name: db
    plan: Starter
    ipAllowList: []
